apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tusky-db-backup.fullname" . }}
  namespace: {{ .Values.namespace }} 
  labels:
    {{- include "tusky-db-backup.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "tusky-db-backup.fullname" . }}
  namespace: {{ .Values.namespace }} 
  labels:
    {{- include "tusky-db-backup.labels" . | nindent 4 }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]  # Added deployments/scale
  verbs: ["get", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tusky-db-backup.fullname" . }}
  namespace: {{ .Values.namespace }} 
  labels:
    {{- include "tusky-db-backup.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "tusky-db-backup.fullname" . }}
  namespace: {{ .Values.namespace }} 
roleRef:
  kind: Role
  name: {{ include "tusky-db-backup.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
