apiVersion: v1
kind: Secret
metadata:
  name: s3bucket-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  accesskey: {{ .Values.bucket.minioAccessKey | b64enc | quote }}
  secretkey: {{ .Values.bucket.minioSecretKey | b64enc | quote }}
